import { CopilotClient } from '@github/copilot-sdk'
import { AccountsStore } from './accounts-store'
import { Account, isDotComAccount } from '../../models/account'
import { Emitter, Disposable } from 'event-kit'
import { resolve } from 'path'

/** Represents the commit details (title and description) generated by Copilot */
export interface ICopilotCommitMessage {
  readonly title: string
  readonly description: string
}

/** Returns the path of the copilot CLI binary. */
export function getCopilotCLIPath(): string {
  return resolve(__dirname, 'copilot')
}

/**
 * System prompt for the Copilot commit message generation session.
 */
const CommitMessageSystemPrompt = `
You're an AI assistant whose job is to concisely summarize code changes into
short, useful commit messages, with a title and a description.

A changeset is given in the git diff output format, affecting one or multiple files.

The commit title should be no longer than 50 characters and should summarize the
contents of the changeset for other developers reading the commit history.

The commit description can be longer, and should provide more context about the
changeset, including why the changeset is being made, and any other relevant
information. The commit description is optional, so you can omit it if the
changeset is small enough that it can be described in the commit title or if you
don't have enough context.

Be brief and concise.

Do NOT include a description of changes in "lock" files from dependency managers
like npm, yarn, or pip (and others), unless those are the only changes in the commit.

Your response must be a JSON object with the attributes "title" and "description"
containing the commit title and commit description. Do not use markdown to wrap
the JSON object, just return it as plain text. For example:

{
  "title": "Fix issue with login form",
  "description": "The login form was not submitting correctly. This commit fixes that issue by adding a missing \`name\` attribute to the submit button."
}
`

/**
 * This store manages the Copilot client lifecycle based on the user's
 * GitHub.com account. It recreates the client when the account or token
 * changes that use Copilot features.
 *
 * Currently, Copilot is only available for GitHub.com accounts.
 */
export class CopilotStore {
  private readonly emitter = new Emitter()
  private client: CopilotClient | null = null
  private currentAccount: Account | null = null

  public constructor(private readonly accountsStore: AccountsStore) {
    this.accountsStore.onDidUpdate(this.onAccountsUpdated)
    this.initializeFromAccounts()
  }

  /**
   * Initialize the Copilot client from the current accounts.
   */
  private async initializeFromAccounts(): Promise<void> {
    const accounts = await this.accountsStore.getAll()
    this.onAccountsUpdated(accounts)
  }

  /**
   * Handler for account updates. Recreates the Copilot client if the
   * GitHub.com account has changed.
   */
  private onAccountsUpdated = (accounts: ReadonlyArray<Account>): void => {
    // Copilot is only available on GitHub.com, so we look for a dotcom account
    const dotComAccount = accounts.find(isDotComAccount) ?? null

    // Check if the account or token has changed
    if (this.shouldRecreateClient(dotComAccount)) {
      this.recreateClient(dotComAccount)
    }
  }

  /**
   * Determines if the client should be recreated based on account changes.
   */
  private shouldRecreateClient(newAccount: Account | null): boolean {
    if (this.currentAccount === null && newAccount === null) {
      return false
    }

    if (this.currentAccount === null || newAccount === null) {
      return true
    }

    // Recreate if the account ID or token has changed
    return (
      this.currentAccount.id !== newAccount.id ||
      this.currentAccount.token !== newAccount.token
    )
  }

  /**
   * Stops the existing client and creates a new one for the given account.
   */
  private recreateClient(account: Account | null): void {
    this.stopClient()
    this.currentAccount = account

    if (account === null || !account.token) {
      log.info('CopilotStore: No GitHub.com account available, client stopped')
      return
    }

    this.client = new CopilotClient({
      cliPath: getCopilotCLIPath(),
      logLevel: 'all',
      autoStart: true,
      githubToken: account.token,
    })

    log.info(`CopilotStore: Created new client for '${account.login}'`)
  }

  /**
   * Stops the current Copilot client if one exists.
   */
  private async stopClient(): Promise<void> {
    if (this.client !== null) {
      try {
        await this.client.stop()
      } catch (e) {
        log.warn('CopilotStore: Error stopping client', e)
      }
      this.client = null
    }
  }

  /**
   * Generates a commit message for the given diff using Copilot.
   *
   * @param diff The diff of changes to be committed, in git format
   * @returns Commit details (title and description) generated by Copilot
   * @throws Error if no GitHub.com account is available or if generation fails
   */
  public async generateCommitMessage(
    diff: string
  ): Promise<ICopilotCommitMessage> {
    if (this.client === null || this.currentAccount === null) {
      throw new Error(
        'Cannot generate commit message: No GitHub.com account available'
      )
    }

    let session: Awaited<
      ReturnType<CopilotClient['createSession']>
    > | null = null

    try {
      // Create a session for commit message generation
      session = await this.client.createSession({
        model: 'gpt-5-mini',
        reasoningEffort: 'low',
        systemMessage: {
          mode: 'replace',
          content: CommitMessageSystemPrompt,
        },
      })

      // Send the diff and wait for response
      const response = await session.sendAndWait({ prompt: diff }, 30000)

      if (!response || !response.data.content) {
        throw new Error('No response from Copilot')
      }

      // Parse the JSON response
      const content = response.data.content
      // Try to extract JSON from markdown code blocks if present
      const jsonMatch =
        content.match(/```json\s*([\s\S]*?)```/) ||
        content.match(/```\s*([\s\S]*?)```/)
      const jsonStr = jsonMatch ? jsonMatch[1].trim() : content.trim()

      return JSON.parse(jsonStr)
    } catch (e) {
      log.warn('CopilotStore: Failed to generate commit message', e)
      throw e
    } finally {
      // Clean up the session
      if (session !== null) {
        try {
          await session.destroy()
        } catch {
          // Ignore cleanup errors
        }
      }
    }
  }

  /**
   * Returns whether the Copilot client is available (i.e., a GitHub.com
   * account is signed in).
   */
  public get isAvailable(): boolean {
    return this.client !== null && this.currentAccount !== null
  }

  /**
   * Returns the currently associated GitHub.com account, if any.
   */
  public get account(): Account | null {
    return this.currentAccount
  }

  /**
   * Register a function to be called when an error occurs.
   */
  public onDidError(fn: (e: Error) => void): Disposable {
    return this.emitter.on('did-error', fn)
  }

  /**
   * Emits an error event.
   */
  protected emitError(error: Error): void {
    this.emitter.emit('did-error', error)
  }
}
