import { CopilotClient } from '@github/copilot-sdk'

/** Represents the commit details (title and description) generated by Copilot */
export interface ICopilotCommitMessage {
  readonly title: string
  readonly description: string
}

/**
 * Leverages Copilot to generate the commit details (title and description)
 * for a given diff using the Copilot SDK.
 *
 * Note: This implementation uses the Copilot SDK which spawns a local
 * Copilot CLI process. The CLI must be installed and accessible in PATH.
 *
 * @param diff Diff of changes to be committed, in git format
 * @returns Commit details (title and description) generated by Copilot
 */
export async function generateCommitMessage(
  copilotEndpoint: string,
  diff: string
): Promise<ICopilotCommitMessage> {
  // Create a Copilot SDK client
  // This will spawn a local Copilot CLI process
  const client = new CopilotClient({
    autoStart: true,
  })

  try {
    // Create a session for commit message generation
    const session = await client.createSession({
      model: 'gpt-5-mini',
      systemMessage: {
        mode: 'replace',
        content: `
You're an AI assistant whose job is to concisely summarize code changes into
short, useful commit messages, with a title and a description.

A changeset is given in the git diff output format, affecting one or multiple files.

The commit title should be no longer than 50 characters and should summarize the
contents of the changeset for other developers reading the commit history.

The commit description can be longer, and should provide more context about the
changeset, including why the changeset is being made, and any other relevant
information. The commit description is optional, so you can omit it if the
changeset is small enough that it can be described in the commit title or if you
don't have enough context.

Be brief and concise.

Do NOT include a description of changes in "lock" files from dependency managers
like npm, yarn, or pip (and others), unless those are the only changes in the commit.

Your response must be a JSON object with the attributes "title" and "description"
containing the commit title and commit description. Do not use markdown to wrap
the JSON object, just return it as plain text. For example:

{
  "title": "Fix issue with login form",
  "description": "The login form was not submitting correctly. This commit fixes that issue by adding a missing \`name\` attribute to the submit button."
}
  `,
      },
    })

    // Send the diff and wait for response
    const response = await session.sendAndWait(
      { prompt: diff },
      30000 // 30 second timeout
    )

    // Clean up
    await session.destroy()
    await client.stop()

    if (!response || !response.data.content) {
      throw new Error('No response from Copilot')
    }

    // Parse the JSON response
    const content = response.data.content
    // Try to extract JSON from markdown code blocks if present
    const jsonMatch =
      content.match(/```json\s*([\s\S]*?)```/) ||
      content.match(/```\s*([\s\S]*?)```/)
    const jsonStr = jsonMatch ? jsonMatch[1].trim() : content.trim()

    return JSON.parse(jsonStr)
  } catch (e) {
    log.warn('generateCommitMessage: failed to generate commit message', e)
    // Ensure client is stopped even on error
    try {
      await client.stop()
    } catch {
      // Ignore cleanup errors
    }
    throw e
  }
}
