name: PR external
on:
  pull_request_target:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    # pull_request.head.label = {owner}:{branch}
    if: startsWith(github.event.pull_request.head.label, 'desktop:') == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: read
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: external
