name: Remove triage label
on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  remove-triage-label-from-issues:
    if: github.event.label.name != 'triage'
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit "$NUMBER" --remove-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
