name: 'Marks stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *' # 1:30 AM UTC

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-label: 'stale, triage' # The label that will be added to the issues when automatically marked as stale
          start-date: '2024-11-25T00:00:00Z' # Skip stale action for issues/PRs created before it
          days-before-stale: 365
          days-before-close: -1 # If -1, the issues nor pull requests will never be closed automatically.
          days-before-pr-stale: -1 # If  -1, no pull requests will be marked as stale automatically.
          exempt-issue-labels: 'never-stale, help wanted, ' # issues labeled as such will be excluded them from being marked as stale
